"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Icon } from "@/components/icons";
import { SiteFooter, SiteHeader } from "@/components/site-chrome";
import { TourDialog } from "@/components/tour-dialog";
import { brand, destinations, faq, gallery, tours, whatsappUrl } from "@/lib/wale-content";

type Section = "about" | "tours" | "destinations" | "gallery" | "faq" | "contact";

const benefits = ["Local Guide", "Private Tour", "Flexible Itinerary", "Fast WhatsApp Support", "Easy Booking", "Personalized Service"];

export default function ContentPage({ section, title }: { section: Section; title: string }) {
  const [scrollY, setScrollY] = useState(0);
  const [showPhotos, setShowPhotos] = useState(false);
  useEffect(() => {
    const update = () => setScrollY(window.scrollY);
    window.addEventListener("scroll", update, { passive: true });
    return () => window.removeEventListener("scroll", update);
  }, []);
  return <>
    <SiteHeader hidden={scrollY > 75} />
    <main id="main-content" className="bg-paper-2 pt-[60px] md:pt-[72px]">
      <nav aria-label="Breadcrumb" className="border-b border-card-line bg-paper"><ol className="mx-auto flex max-w-[1280px] items-center gap-2 overflow-x-auto px-5 py-1.5 text-[12.5px] md:px-10"><li><Link href="/" className="text-mute hover:text-coral">Home</Link></li><li aria-hidden="true" className="text-faint">/</li><li className="truncate text-ink">{title}</li></ol></nav>
      <div className="mx-auto max-w-[1280px] px-5 pt-10 md:px-10 md:pt-14"><p className="font-mono text-[10.5px] uppercase tracking-[.16em] text-coral">Wale Adventure · North Sulawesi, Indonesia</p><h1 className="mt-2 font-serif text-[28px] font-semibold leading-[1.06] tracking-[-.01em] text-ink md:text-[42px]">{title}</h1>
        {section === "about" && <div className="mt-8 grid gap-8 lg:grid-cols-[minmax(0,1fr)_minmax(340px,.8fr)] lg:items-center"><div><p className="font-serif text-[26px] leading-[1.28] text-ink md:text-[38px]">At Wale Adventure, we believe every journey should become a lifetime memory.</p><p className="mt-5 text-[16px] leading-[1.75] text-ink-2">Based in North Sulawesi, Indonesia, we create authentic private tours through Bunaken National Marine Park, Tangkoko Nature Reserve, Tomohon and the Minahasa Highlands.</p><p className="mt-4 text-[16px] leading-[1.75] text-ink-2">Our local team shares the region’s culture, nature and hospitality through professional guiding, personal service and carefully planned itineraries—from your first inquiry to the end of your trip.</p><p className="mt-5 font-serif text-[22px] italic text-coral">Discover North Sulawesi with locals who truly know it best.</p></div><div className="relative aspect-[4/3] overflow-hidden rounded-lg bg-ink/10"><Image src="/images/wale/hero.png" alt="Travelers exploring local culture with Wale Adventure in North Sulawesi" fill sizes="(max-width: 1024px) 100vw, 50vw" className="object-cover" /></div><ul className="grid gap-x-8 sm:grid-cols-2 lg:col-span-2 lg:grid-cols-3">{benefits.map((item) => <li key={item} className="border-t border-card-line py-4 text-[15px] text-ink-2"><span className="me-3 inline-block h-2 w-2 rounded-full border border-coral" />{item}</li>)}</ul></div>}
        {(section === "tours" || section === "destinations") && <p className="mt-4 max-w-[65ch] text-[16px] leading-relaxed text-mute">{section === "tours" ? "Choose a private North Sulawesi experience. Send your dates and interests to our local team for availability and a quotation." : "From rainforest wildlife to highland scenery and coral reefs, explore the places that make North Sulawesi distinctive."}</p>}
        {(section === "tours" || section === "destinations") && <ul className="mt-8 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{(section === "tours" ? tours : destinations.map((destination) => ({ title: destination.title, description: destination.description, image: destination.image, imageAlt: destination.alt, slug: destination.tour.slug, duration: "North Sulawesi" }))).map((item) => <li key={item.title}><Link href={`/tours/${item.slug}`} className="group/insp flex h-full flex-col overflow-hidden rounded-lg bg-card shadow-tile-soft transition-shadow hover:shadow-sheet"><span className="relative block aspect-[16/10] w-full overflow-hidden bg-ink"><Image src={item.image} alt={item.imageAlt} fill sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 33vw" className="object-cover transition-transform duration-500 group-hover/insp:scale-[1.04]" /></span><span className="flex flex-1 flex-col items-center px-6 py-6 text-center"><span className="font-mono text-[11px] uppercase tracking-[.12em] text-ochre">{item.duration}</span><span className="mt-2.5 font-serif text-[22px] font-semibold leading-snug text-ink transition-colors group-hover/insp:text-coral">{item.title}</span><span className="mt-3 text-[14px] leading-relaxed text-mute">{item.description}</span><span className="mt-auto pt-6 font-semibold uppercase tracking-[.08em] text-coral">View Tour</span></span></Link></li>)}</ul>}
        {section === "gallery" && <><p className="mt-4 max-w-[65ch] text-[16px] leading-relaxed text-mute">Wildlife, highland culture and marine experiences from across North Sulawesi.</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{gallery.map((photo) => <button key={photo.src} type="button" onClick={() => setShowPhotos(true)} aria-label={`View gallery: ${photo.alt}`} className="group relative block aspect-[4/3] overflow-hidden rounded-md bg-ink/10"><Image src={photo.src} alt={photo.alt} fill sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 33vw" className="object-cover transition-transform duration-500 group-hover:scale-[1.04]" /></button>)}</div></>}
        {section === "faq" && <div className="mx-auto mt-8 max-w-[900px] border-t border-card-line">{faq.map((item) => <details key={item.question} className="group/faq border-b border-card-line"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 py-5 text-start text-[16px] font-semibold text-ink transition-colors hover:text-coral md:text-[17px] [&::-webkit-details-marker]:hidden">{item.question}<Icon name="chevron" className="h-4 w-4 shrink-0 text-mute transition-transform group-open/faq:rotate-180" /></summary><p className="pb-6 text-[15.5px] leading-[1.7] text-ink-2 md:text-[16px]">{item.answer}</p></details>)}</div>}
        {section === "contact" && <div className="mt-8 grid gap-8 rounded-2xl border border-card-line bg-card p-7 md:grid-cols-2 md:p-10"><div><p className="font-serif text-[24px] font-semibold text-ink">Tell us about your trip</p><p className="mt-3 text-[15.5px] leading-relaxed text-ink-2">Share your preferred destination, travel dates and interests. Our team will confirm availability, itinerary details and a quotation.</p><a href={whatsappUrl()} target="_blank" rel="noreferrer" className="mt-6 inline-flex rounded-full bg-coral px-7 py-3.5 text-[12.5px] font-semibold uppercase tracking-[.08em] text-paper transition-colors hover:bg-coral-deep">Chat on WhatsApp</a></div><div><p className="font-mono text-[10.5px] uppercase tracking-[.16em] text-mute">Contact Information</p><ul className="mt-4 space-y-4"><li><a href={`mailto:${brand.email}`} className="flex items-center gap-3 text-[16px] text-ink-2 hover:text-coral"><Icon name="mail" className="h-5 w-5 text-coral" />{brand.email}</a></li><li><a href={whatsappUrl()} target="_blank" rel="noreferrer" className="flex items-center gap-3 text-[16px] text-ink-2 hover:text-coral"><Icon name="whatsapp" className="h-5 w-5 text-coral" />{brand.displayPhone}</a></li><li><a href={brand.instagram} target="_blank" rel="noreferrer" className="text-[15px] text-ink-2 hover:text-coral">Instagram</a><span className="px-2 text-faint">·</span><a href={brand.facebook} target="_blank" rel="noreferrer" className="text-[15px] text-ink-2 hover:text-coral">Facebook</a></li><li className="text-[14px] text-mute">{brand.location}</li></ul></div></div>}
      </div>
      <div className="pb-14 pt-14 md:pb-20"><SiteFooter /></div>
    </main>
    {showPhotos && <TourDialog kind="photos" photoSources={gallery} onClose={() => setShowPhotos(false)} />}
  </>;
}
