"use client";

import Image from "next/image";
import { useState } from "react";
import { Icon } from "./icons";
import { Tour, featuredTours, whatsappUrl } from "@/lib/wale-content";

const tabs = [["highlights", "Overview"], ["itinerary", "Experiences"], ["dates", "Plan your trip"]];

export function TourHeader({ compact, active, tour }: { compact: boolean; active: string; tour?: Tour }) {
  const scheduled = tour?.kind === "scheduled" ? tour : undefined;
  const title = tour?.title ?? "Explore North Sulawesi With Local Experts";
  const primary = tour ? "Tour details" : "Explore Our Tours";
  return <div data-tour-bar="true" className={compact ? "fixed inset-x-0 top-0 z-30" : "relative z-30"}>
    <div className={`relative overflow-hidden border-b border-card-line bg-paper transition-shadow duration-300 ${compact ? "shadow-tile-soft" : ""}`}>
      {!compact && <Image src="/images/title-fan.svg" alt="" aria-hidden="true" width={560} height={520} unoptimized className="pointer-events-none absolute -right-24 top-0 hidden h-full w-[560px] select-none lg:block" />}
      <div className={`relative mx-auto flex max-w-[1280px] flex-wrap items-end justify-between gap-x-8 px-5 transition-[padding] duration-300 md:flex-nowrap md:items-center md:px-10 ${compact ? "gap-y-2 py-2.5" : "gap-y-4 py-5 md:py-6"}`}>
        <div className="min-w-0 flex-1"><p className={`flex items-center gap-2 font-mono text-[10.5px] uppercase tracking-[.16em] text-mute transition-all duration-300 ${compact ? "h-0 overflow-hidden opacity-0" : "opacity-100"}`}><svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" className="h-3 w-3 text-coral"><rect x="3" y="14" width="5" height="7" rx="1.5"/><rect x="9.5" y="9.5" width="5" height="11.5" rx="1.5"/><rect x="16" y="5" width="5" height="16" rx="1.5" opacity=".28"/></svg>{tour ? `${tour.kind === "custom" ? "Custom" : "Private"} ${tour.region} Tour` : "Local guides · Private tours · North Sulawesi"}</p>
          <h1 className={`font-serif text-ink transition-all duration-300 ${compact ? "line-clamp-2 text-[19px] font-normal leading-tight md:line-clamp-none md:text-[22px]" : "mt-1.5 text-[28px] font-semibold leading-[1.06] tracking-[-.01em] md:text-[42px]"}`}>{tour || compact ? title : <>Explore North Sulawesi<br className="hidden lg:block" />{" "}With Local Experts</>}</h1>
          <div className={`flex flex-wrap items-baseline gap-x-4 transition-all duration-300 ${compact ? "mt-1 gap-y-0" : "mt-2.5 gap-y-1 md:mt-3"}`}><span className={`font-semibold uppercase tracking-[.08em] text-ink ${compact ? "text-[11.5px]" : "text-[13px]"}`}>{scheduled ? scheduled.duration : tour ? "Custom tour" : "Private tours"}</span><span className="flex items-baseline gap-1.5"><span className={`font-serif font-semibold text-coral transition-all duration-300 ${compact ? "text-[18px]" : "text-[24px] md:text-[28px]"}`}>{scheduled ? scheduled.pickup : tour ? "Flexible itinerary" : "Local guides"}</span><span className="text-[12.5px] text-mute">{scheduled ? "pickup" : ""}</span></span></div>
          <div className={`transition-all duration-300 ${compact ? "h-0 overflow-hidden opacity-0" : "mt-2 opacity-100"}`}><p className="text-[9.5px] leading-[1.6] text-faint">{tour ? `Private experiences in ${tour.region}, with personal trip planning.` : "Private tours to Bunaken, Tangkoko, Tomohon and the Minahasa Highlands."}</p><p className="text-[9.5px] leading-[1.6] text-faint">Send your travel dates for itinerary details, availability and a quotation.</p></div>
        </div>
        <div className={`flex shrink-0 flex-col gap-1.5 md:w-auto md:items-end ${compact ? "w-auto" : "w-full"}`}><div className="flex items-stretch gap-2.5 md:gap-3"><a href={tour ? "#dates" : "#itinerary"} className={`${compact ? "hidden px-5 py-2 text-[11.5px] md:flex" : "flex flex-1 px-6 py-3 text-[12.5px] md:flex-none"} items-center justify-center whitespace-nowrap rounded-full border border-ink font-semibold uppercase tracking-[.08em] text-ink transition-colors hover:border-coral hover:text-coral`}>{tour ? primary : <><span className="hidden md:inline">{primary}</span><span className="md:hidden">Explore Tours</span></>}</a><a href={whatsappUrl(tour ? `Hello Wale Adventure, I'm interested in the ${tour.title}. Please confirm availability and the final price for my travel dates and group size.` : undefined)} target="_blank" rel="noreferrer" className={`${compact ? "px-5 py-2 text-[11.5px]" : "flex-1 px-6 py-3 text-[12.5px] md:flex-none"} flex items-center justify-center whitespace-nowrap rounded-full bg-coral font-semibold uppercase tracking-[.08em] text-paper transition-colors hover:bg-coral-deep`}>Book Your Trip</a></div></div>
      </div>
    </div>
    <nav aria-label="Sections" className="border-b border-card-line bg-paper-2/95 backdrop-blur-sm"><ul className="hide-scrollbar mx-auto flex max-w-[1280px] gap-7 overflow-x-auto px-5 md:gap-10 md:px-10">{tabs.map(([id, label]) => <li key={id} className="shrink-0"><a href={`#${id}`} aria-current={active === id ? "true" : undefined} className={`group/tab relative block py-3 text-[12px] font-semibold uppercase tracking-[.1em] transition-colors md:text-[13px] ${active === id ? "text-coral" : "text-ink-2 hover:text-ink"}`}>{label}<span aria-hidden="true" className={`absolute inset-x-0 bottom-0 h-[2px] bg-coral transition-opacity ${active === id ? "opacity-100" : "opacity-0 group-hover/tab:opacity-30"}`} /></a></li>)}</ul></nav>
  </div>;
}

export function RouteBar({ shown, tour }: { shown: boolean; tour?: Tour }) {
  const [expanded, setExpanded] = useState(false);
  const entries = tour?.kind === "scheduled" ? tour.stages.map((stage) => stage.title) : tour ? [tour.destination] : featuredTours.map((item) => item.title);
  return <div aria-hidden={!shown} className="pointer-events-none fixed inset-x-0 bottom-0 z-50 flex justify-center px-3 pb-3 md:px-6 md:pb-5"><div inert={!shown} className={`pointer-events-auto w-full max-w-[1160px] overflow-hidden rounded-xl bg-ink text-paper shadow-sheet transition-[transform,opacity] duration-500 motion-reduce:transition-none ${shown ? "translate-y-0 opacity-100" : "pointer-events-none translate-y-8 opacity-0"}`}><div className="flex items-center gap-4 px-4 py-3.5 md:gap-6 md:px-6 md:py-4"><button type="button" aria-expanded={expanded} aria-label={expanded ? "Hide tour experiences" : "Show tour experiences"} onClick={() => setExpanded(!expanded)} className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg text-paper/80 transition-colors hover:bg-paper/10 hover:text-paper"><Icon name="route" className="h-5 w-5" /></button><div className="min-w-0 flex-1 text-end"><p className="line-clamp-2 text-[13.5px] font-semibold leading-tight md:truncate md:text-[17px]">{tour?.title ?? "Explore North Sulawesi With Local Experts"}</p><p className="mt-0.5 text-[12px] text-coral md:text-[13.5px]">Private tours · Local guides</p></div><a href={whatsappUrl(tour ? `Hello Wale Adventure, I'm interested in the ${tour.title}. Please confirm availability and the final price for my travel dates and group size.` : undefined)} target="_blank" rel="noreferrer" className="flex shrink-0 items-center justify-center rounded-full bg-coral px-5 py-2.5 text-[11.5px] font-semibold uppercase tracking-[.08em] text-paper transition-colors hover:bg-coral-deep md:px-7 md:py-3 md:text-[12.5px]">Book Your Trip</a></div><div hidden={!expanded} className="border-t border-paper/15"><p className="px-4 pt-4 font-mono text-[10px] uppercase tracking-[.16em] text-paper/50 md:px-6">{tour ? "Tour experiences" : "Choose an experience"}</p><ul className="hide-scrollbar flex gap-6 overflow-x-auto px-4 pt-3 pb-5 md:gap-8 md:px-6">{entries.map((entry, index) => <li key={entry} className="w-[168px] shrink-0 md:w-[190px]"><a href="#itinerary" className="block border-t-2 border-paper/20 pt-3 transition-colors hover:border-coral"><span className="block text-[12.5px] text-coral">{tour ? "Experience" : "Explore"} {index + 1}</span><span className="mt-1 line-clamp-2 block text-[13.5px] font-semibold leading-snug text-paper">{entry}</span></a></li>)}</ul></div></div></div>;
}
